### PR TITLE
using available port if default is bound

### PR DESCRIPTION
**Pull request by 1vipulgupta**
Used `try_bind` instead of `bind` which will panic if port is busy, and case matching on it. In Error case, i am updating port by adding 1 and retrying for port.

### CODE REVIEW

**Review by srid — CHANGES_REQUESTED** [review]
I should have clarified in the issue. I think it is best if you re-use a crate for this, rather than writing it by hand. Less code is better.

There is: https://lib.rs/crates/get-port

**Comment by srid** [comment]
Or, we can do it without any new crates by trying port `0` if the default port is unavailable. cf. https://github.com/hyperium/tonic/issues/667#issuecomment-847847088

I wonder if port 0 works in Axum

**Comment by 1vipulgupta** [comment]
Even if we get Port we still need some computation part to get ip which is configured in `Cargo.toml`. or we want to run on `127.0.0.1` always ?

**Comment by 1vipulgupta** [comment]
Adding Port 0 is not working, it is giving `The web page at http://127.0.0.1:0/ might be temporarily down or it may have moved permanently to a new web address.`

**Review by srid — COMMENTED** [review]
@1vipulgupta Just tried out locally, it doesn't work for me:

```
❯ nix run
warning: Git tree '/Users/srid/code/nix-browser' is dirty
thread 'main' panicked at 'error binding to 127.0.0.1:3000: error creating server listener: Address already in use (os error 48)', /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/hyper-0.14.27/src/server/server.rs:79:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`just watch` to the left (using port 3000), and `nix run` to right run latter: 

image

I'd expect `nix run` to use a new port.

**Comment by srid** [comment]
I also see this in `just watch`,

image

which probably means our approach is wrong here.

**Comment by srid** [comment]
> I wonder if port 0 works in Axum

Actually I just confirmed that this does indeed work.

**Pull request merged**
